# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointInterpolation
                                 A QGIS plugin
 This plugin interpolates points between two points and draw points at specified distance on that line.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-04
        copyright            : (C) 2019 by shehar bano
        email                : sheharbanoafzal@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointInterpolation class from file PointInterpolation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .points_interpolation import PointInterpolation
    return PointInterpolation(iface)
